lib/zaryn_web/router.ex
defmodule ZarynWeb.Router do
  @moduledoc false

  use ZarynWeb, :router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:put_root_layout, {ZarynWeb.LayoutView, :root})
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  # Add the on chain implementation of the archethic.io at the root of the webserver
  # TODO: review to put it on every node or as proxy somewhere forwarding to a specific transaction chain explorer
  scope "/", ZarynWeb do
    pipe_through(:browser)

    get("/", RootController, :index)
    get("/up", UpController, :up)
    get("/metrics", MetricsController, :index)
    live_dashboard("/dashboard", metrics: Zaryn.Telemetry)
  end

  scope "/explorer", ZarynWeb do
    pipe_through(:browser)

    live("/", ExplorerIndexLive)
    live("/transactions", TransactionListLive)
    live("/transaction/:address", TransactionDetailsLive)
    get("/chain", ExplorerController, :chain)
    live("/nodes", NodeListLive)
    live("/node/:public_key", NodeDetailsLive)
    live("/code/viewer", CodeViewerLive)
    live("/code/proposals", CodeProposalsLive)
    live("/code/proposal/:address", CodeProposalDetailsLive)
    get("/code/download", CodeController, :download)
  end

  scope "/api" do
    pipe_through(:api)

    get(
      "/last_transaction/:address/content",
      ZarynWeb.API.TransactionController,
      :last_transaction_content
    )

    post("/transaction", ZarynWeb.API.TransactionController, :new)

    forward(
      "/graphiql",
      Absinthe.Plug.GraphiQL,
      schema: ZarynWeb.GraphQLSchema,
      socket: ZarynWeb.UserSocket
    )

    forward(
      "/",
      Absinthe.Plug,
      schema: ZarynWeb.GraphQLSchema
    )
  end
end

lib/zaryn/governance/code.ex
defmodule Zaryn.Governance.Code do
  @moduledoc """
  Provide functions to handle the code management and deployment
  """

  alias Zaryn.Crypto

  alias __MODULE__.CICD
  alias __MODULE__.Proposal

  alias Zaryn.Governance.Pools

  alias Zaryn.Replication

  alias Zaryn.TransactionChain

  alias Zaryn.Utils

  @src_dir Application.compile_env(:zaryn, :src_dir)

  @doc """
  List the source files from the master branch
  """
  @spec list_source_files() :: list(binary())
  def list_source_files do
    {files, 0} = System.cmd("git", ["ls-tree", "-r", "HEAD", "--name-only"], cd: @src_dir)
    String.split(files, "\n", trim: true)
  end

  @doc """
  Show the content of a file from the last changes
  """
  @spec file_content(binary()) :: binary()
  def file_content(filename) when is_binary(filename) do
    {content, 0} = System.cmd("git", ["show", "HEAD:#{filename}"], cd: @src_dir)
    String.trim(content)
  end

  @doc """
  Determine if the code proposal can be deployed into testnet
  """
  @spec testnet_deployment?(binary()) :: boolean()
  def testnet_deployment?(proposal_address) when is_binary(proposal_address) do
    storage_nodes = Replication.chain_storage_nodes(proposal_address)

    if Utils.key_in_node_list?(storage_nodes, Crypto.first_node_public_key()) do
      approvals = TransactionChain.list_signatures_for_pending_transaction(proposal_address)
      ratio = length(approvals) / length(Pools.members_of(:technical_council))
      ratio >= Pools.threshold_acceptance_for(:technical_council)
    else
      false
    end
  end

  @doc """
  Deploy the proposal into a dedicated testnet
  """
  @spec deploy_proposal_testnet(Proposal.t()) :: :ok
  defdelegate deploy_proposal_testnet(prop), to: CICD, as: :run_testnet!

  @doc """
  Ensure the code proposal is valid according to the defined rules:
  - Version in the code proposal must be a direct successor of the current running version.
  - Git diff/patch must be valid.
  """
  @spec valid_proposal?(Proposal.t()) :: boolean()
  def valid_proposal?(prop = %Proposal{version: version}) do
    with true <- succeessor_version?(current_version(), version),
         true <- applicable_proposal?(prop) do
      true
    else
      _ ->
        false
    end
  end

  @doc """
  Ensure the code proposal is an applicable on the current branch.
  """
  @spec applicable_proposal?(Proposal.t()) :: boolean()
  def applicable_proposal?(
        %Proposal{changes: changes, address: address},
        src_dir \\ @src_dir
      ) do
    random = :crypto.strong_rand_bytes(4) |> Base.encode16()
    prop_file = Path.join(System.tmp_dir!(), "prop_#{random}_#{Base.encode16(address)}")
    File.write!(prop_file, changes)

    cmd_options = [stderr_to_stdout: true, cd: src_dir]
    git = fn args -> System.cmd("git", args, cmd_options) end

    res =
      case status() do
        {:clean, _} ->
          git.(["apply", "--check", prop_file])

        otherwise ->
          {:error, otherwise}
      end

    File.rm(prop_file)

    match?({_, 0}, res)
  end

  @doc """
  Return tuple {state, branch_name} where state could be :clean or :dirty or
  {:error, whatever}
  """
  @spec status() :: {:clean, String.t()} | {:dirty, String.t()} | {:error, any}
  def status(src_dir \\ @src_dir) do
    git = fn args -> System.cmd("git", args, stderr_to_stdout: true, cd: src_dir) end

    case git.(["symbolic-ref", "--short", "HEAD"]) do
      {branch, 0} ->
        case git.(["status", "--porcelain"]) do
          {"", 0} ->
            {:clean, String.trim(branch)}

          {_, 0} ->
            {:dirty, String.trim(branch)}

          otherwise ->
            {:error, otherwise}
        end

      otherwise ->
        {:error, otherwise}
    end
  end

  @doc """
  Return true if version2 is a direct successor of version1.
  Note that build and patch must not be set.

  ## Examples

    iex> Code.succeessor_version?("1.1.1", "1.1.2")
    true

    iex> Code.succeessor_version?("1.1.1", "1.2.0")
    true

    iex> Code.succeessor_version?("1.1.1", "2.0.0")
    true

    iex> Code.succeessor_version?("1.1.1", "1.2.2")
    false

    iex> Code.succeessor_version?("1.1.1", "1.2.1")
    false

    iex> Code.succeessor_version?("1.1.1", "1.1.2-pre0")
    false
  """
  @spec succeessor_version?(binary | Version.t(), binary | Version.t()) :: boolean
  def succeessor_version?(version1, version2)
      when is_binary(version1) and is_binary(version2) do
    succeessor_version?(Version.parse!(version1), Version.parse!(version2))
  end

  def succeessor_version?(
        %Version{major: ma, minor: mi, patch: pa1, pre: [], build: nil},
        %Version{major: ma, minor: mi, patch: pa2, pre: [], build: nil}
      ),
      do: pa1 + 1 == pa2

  def succeessor_version?(
        %Version{major: ma, minor: mi1, patch: _, pre: [], build: nil},
        %Version{major: ma, minor: mi2, patch: 0, pre: [], build: nil}
      ),
      do: mi1 + 1 == mi2

  def succeessor_version?(
        %Version{major: ma1, minor: _, patch: _, pre: [], build: nil},
        %Version{major: ma2, minor: 0, patch: 0, pre: [], build: nil}
      ),
      do: ma1 + 1 == ma2

  def succeessor_version?(%Version{}, %Version{}), do: false

  defp current_version do
    :zaryn |> Application.spec(:vsn) |> List.to_string()
  end

  @spec list_proposal_CI_logs(binary()) :: Enumerable.t()
  defdelegate list_proposal_CI_logs(address), to: CICD, as: :get_log
end

lib/zaryn/governance/code/CICD.ex
defmodule Zaryn.Governance.Code.CICD do
  @moduledoc ~S"""
    Provides CICD pipeline for `Zaryn.Governance.Code.Proposal`

    The evolution of zaryn-node could be represented using following stages:

    * Init - when source code is compiled into zaryn-node (not covered here)
    * CI - zaryn-node is verifying a proposal and generating a release upgrade
    * CD - zaryn-node is forking a testnet to verify release upgrade

  In each stage a transition from a source to a result could happen

      | Stage | Source           | Transition   | Result         |
      |-------+------------------+--------------+----------------|
      | Init  | Code             | compile      | Release        |
      | CI    | Code, Proposal   | run CI tests | CiLog, Upgrade |
      | CD    | Release, Upgrade | run testnet  | TnLog, Release |

  where
    * Code - a source code of zaryn-node
    * Propsal - a code proposal transaction
    * Release - a release of zaryn-node
    * Upgrade - an upgrade to a release of zaryn-node
    * CiLog - unit tests and type checker logs
    * TnLog - logs retrieved from running testnet fork

  ## CI
  Given a `Code.Proposal` the `CICD.run_ci!/1` should generate: a log of
  application of the `Proposal` to the `Code`, a release upgrade which is a
  delta between previous release and new release, and a new version of
  `zaryn-proposal-validator` escript.

  ## CD
  Given a `Code.Proposal` the `CICD.run_testnet!/1` should start a testnet with
  few `zaryn-node`s and one `zaryn-validator`. The `zaryn-validator` runs
  `zaryn-proposal-validator` escript and gathers metrics from `zaryn-node`s.
  The `zaryn-proposal-validator` escript runs benchmarks and playbooks before
  and after upgrade.
  """

  alias Zaryn.Governance.Code.Proposal

  use Knigge, otp_app: :zaryn, default: __MODULE__.Docker

  @doc """
  Start CICD
  """
  @callback child_spec(any()) :: Supervisor.child_spec()

  @doc """
  Execute the continuous integration of the code proposal
  """
  @callback run_ci!(Proposal.t()) :: :ok

  @doc """
  Return CI log from the proposal address
  """
  @callback get_log(binary()) :: {:ok, binary()} | {:error, term}

  @doc """
  Execute the continuous delivery of the code proposal to a testnet
  """
  @callback run_testnet!(Proposal.t()) :: :ok

  @doc """
  Remove all artifacts generated during `run_ci!/1` and `run_testnet!/1`
  """
  @callback clean(address :: binary()) :: :ok
end

lib/zaryn_web/controllers/code_controller.ex
defmodule ZarynWeb.CodeController do
  @moduledoc false
  use ZarynWeb, :controller

  alias Zaryn.Utils

  # alias Zaryn.TransactionChain

  # alias ZarynWeb.CodeProposalDetailsLive
  # alias ZarynWeb.ExplorerView

  @src_dir Application.compile_env(:zaryn, :src_dir)

  # def show_proposal(conn, %{"address" => address}) do
  #   # case Base.decode16(address, case: :mixed) do
  #   #   {:ok, addr} ->
  #   #     if TransactionChain.transaction_ko?(addr) do
  #   #       conn
  #   #       |> put_view(ExplorerView)
  #   #       |> render("ko_transaction.html", address: addr, errors: [])
  #   #     else
  #   #       live_render(conn, CodeProposalDetailsLive, session: %{"address" => addr})
  #   #     end
  #   #   _ ->
  #       live_render(conn, CodeProposalDetailsLive, session: %{"address" => address})
  #   # end
  # end

  def download(conn, _) do
    archive_file = Utils.mut_dir("priv/zaryn_node.zip")

    case System.cmd("git", ["archive", "-o", archive_file, "master"], cd: @src_dir) do
      {"", 0} ->
        conn
        |> put_resp_content_type("application/zip, application/octet-stream")
        |> put_resp_header("Content-disposition", "attachment; filename=\"zaryn_node.zip\"")
        |> send_file(200, archive_file)

      {reason, status} ->
        conn
        |> put_status(500)
        |> json(%{status: status, message: reason})
    end
  end
end

lib/zaryn_web/views/code_view.ex
defmodule ZarynWeb.CodeView do
  @moduledoc false

  use ZarynWeb, :view

  def render_tree(tree, expanded_folders) when is_map(tree) and is_list(expanded_folders) do
    Enum.reduce(tree, [], &reduce_node(&1, &2, [], expanded_folders))
    |> Enum.reverse()
  end

  defp reduce_node({filename, subfiles}, acc, path, expanded_folders) do
    elem =
      case Map.keys(subfiles) do
        [] ->
          file_node(filename, path)

        _ ->
          folder_node(filename, subfiles, path, expanded_folders)
      end

    [content_tag(:li, elem) | acc]
  end

  defp file_node(filename, path) do
    content_tag(
      :li,
      [
        content_tag(:a, filename,
          "phx-click": "view",
          "phx-value-filename": Path.join(path, filename)
        )
      ]
    )
  end

  defp folder_node(filename, children, path, expanded_folders) do
    children_tags =
      Enum.reduce(children, [], &reduce_node(&1, &2, Path.join(path, filename), expanded_folders))
      |> Enum.reverse()

    visible? = Enum.any?(expanded_folders, &(Path.join(path, filename) == &1))

    class =
      if visible? do
        ""
      else
        "is-hidden"
      end

    action =
      if visible? do
        "collapse"
      else
        "expand"
      end

    content_tag(
      :li,
      [
        content_tag(:a, filename),
        content_tag(
          :ul,
          [
            children_tags
          ],
          class: class
        )
      ],
      "phx-click": action,
      "phx-value-filename": Path.join(path, filename)
    )
  end

  def version_tag(%Version{major: major, minor: minor, patch: patch}) do
    %Version{major: current_major, minor: current_minor, patch: current_patch} = current_version()

    cond do
      major > current_major ->
        content_tag(:span, ["Major"], class: "tag is-danger is-light")

      minor > current_minor ->
        content_tag(:span, ["Minor"], class: "tag is-warning is-light")

      patch > current_patch ->
        content_tag(:span, ["Patch"], class: "tag is-primary is-light")
    end
  end

  defp current_version do
    {:ok, vsn} = :application.get_key(:zaryn, :vsn)
    Version.parse!(List.to_string(vsn))
  end

  defp format_description(content) do
    {:ok, html, _} = Earmark.as_html(content, gfm: true, breaks: true)
    html
  end
end

lib/zaryn_web/templates/code/proposal_details.html.leex
<%= if assigns[:error] != nil and @error == :invalid_address do %>
    <h1 class="subtitle is-size-4 heading has-text-white">Code proposal - <small>Invalid address</small></h1>
<% else %>
    <h1 class="subtitle is-size-4 heading has-text-white">Code proposal - <small><%= Base.encode16(@address) %></small></h1>
<% end %>

<div class="box">

    <%= cond do %>
        <% assigns[:error] != nil and @error == :invalid_address -> %>
            <p>The proposal address is invalid.</p>
            <hr />
            <div class="mt-4 box has-background-warning-light">
                <small>Please check the transaction address validity.</small>
            </div>
        <% !@exists? -> %>
            <p>The proposal does not exists yet. </p>
            <hr />
            <div class="mt-4 box has-background-warning-light">
                <small>It may appears later. <br />Please retry when the proposal will be processed.</small>
            </div>
        <% true -> %>
        <div class="columns">
            <div class="column">
            <p class="heading">Code proposal</h1>
            <h1 class="subtitle text_wrap">
                <%= Base.encode16(@address) %>
            </h1>
            </div>
        </div>

        <div class="columns is-multiline">
            <div class="column is-10-desktop">
                <p class="heading">Description</p>
                <div class="text_wrap">
                    <%= raw(format_description(@description)) %>
                </div>
            </div>
            <div class="column is-2-desktop">
                <p class="heading">Version</p>
                <%= version_tag(Version.parse!(@version)) %>
                <small>(<%= @version %>)</small>
            </div>
        </div>

        <div class="columns">
            <div class="column">
                <p class="heading">Changes</p>
                <div id="diff_src" style="display: none" phx-hook="Diff"></div>
                <div id="diff"></div>
            </div>
        </div>

        <div class="columns">
            <div class="column">
                <p class="heading">Approvals (2)</p>
                <%= for approval <- @approvals do %>
                    <div class="columns">
                        <div class="column">
                            <%= link to: Routes.live_path(@socket, ZarynWeb.TransactionDetailsLive, Base.encode16(approval)) do%>
                                <span class="text_wrap"><%= Base.encode16(approval) %></span>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

lib/zaryn_web/templates/code/proposal_list.html.leex
<h1 class="subtitle is-size-4 heading has-text-white">Code proposals (<%= Enum.count(@proposals) %>)</h1>

<%= if Enum.count(@proposals) == 0 do %>
    <div class="box">
        <p>There is not code proposals yet !</p>
    </div>
<% end %>

<%= for proposal <- @proposals do %>
<div class="box">
    <div class="columns">
        <div class="column">
            <p class="heading">Transaction address</p>
            <%= link to: Routes.live_path(@socket, ZarynWeb.CodeProposalDetailsLive, Base.encode16(proposal.address)) do%>
                <%= Base.encode16(:binary.part(proposal.address, 0, 13)) %>...
            <% end %>
        </div>
        <div class="column">
            <p class="heading">Transaction date</p>
            <span><%= format_date(proposal.timestamp) %><span>
        </div>
        <div class="column">
            <p class="heading">Sender</p>
            <span><%= Base.encode16(:binary.part(proposal.sender, 0, 13)) %>...<span>
        </div>
        <div class="column">
            <p class="heading">Changes criticality</p>
            <span>
                <%= version_tag(Version.parse!(proposal.version)) %>
                <small>(<%= proposal.version %>)</small>
            </span>
        </div>
        <div class="column">
            <p class="heading">Description</p>
            <span><%= String.slice(proposal.description, 0..50) %><span>
        </div>
        <div class="column">
            <p class="heading">Approvals</p>
            <span><%= proposal.nb_approvals %><span>
        </div>
    </div>
</div>
<% end  %>

lib/zaryn_web/templates/code/viewer.html.leex
<h1 class="subtitle is-size-4 heading has-text-white">Code source viewer</h1>

<div class="box">
    <div class="columns">
        <div class="column"></div>
        <div class="column is-2-desktop">
            <%= link class: "button is-primary is-outlined is-fullwidth", to: Routes.code_path(@socket, :download) do%>
                Download code
            <% end %>
        </div>
    </div>

    <div class="columns">
        <div class="column is-3-desktop">
            <aside class="menu">
                <ul class="menu-list">
                    <li>
                        <ul class="menu-list">
                            <%= render_tree(@tree, @expanded_folders) %>
                        </ul>
                    </li>
                </ul>
            </aside>
        </div>

        <div class="column">
            <%= if @details != nil do %>
            <p class="heading"><%= @details.filename %></p>   
            <pre style="width: 100%" phx-hook="CodeViewer">
                <code class="<%= @details.language %>">
                    <%= @details.content %>
                </code>
            </pre>         
            <% end %>
        </div>
    </div>
</div>