lib/zaryn_web/router.ex
defmodule ZarynWeb.Router do
  @moduledoc false

  use ZarynWeb, :router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:put_root_layout, {ZarynWeb.LayoutView, :root})
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  # Add the on chain implementation of the archethic.io at the root of the webserver
  # TODO: review to put it on every node or as proxy somewhere forwarding to a specific transaction chain explorer
  scope "/", ZarynWeb do
    pipe_through(:browser)

    get("/", RootController, :index)
    get("/up", UpController, :up)
    get("/metrics", MetricsController, :index)
    live_dashboard("/dashboard", metrics: Zaryn.Telemetry)
  end

  scope "/explorer", ZarynWeb do
    pipe_through(:browser)

    live("/", ExplorerIndexLive)
    live("/transactions", TransactionListLive)
    live("/transaction/:address", TransactionDetailsLive)
    get("/chain", ExplorerController, :chain)
    live("/nodes", NodeListLive)
    live("/node/:public_key", NodeDetailsLive)
    live("/code/viewer", CodeViewerLive)
    live("/code/proposals", CodeProposalsLive)
    live("/code/proposal/:address", CodeProposalDetailsLive)
    get("/code/download", CodeController, :download)
  end

  scope "/api" do
    pipe_through(:api)

    get(
      "/last_transaction/:address/content",
      ZarynWeb.API.TransactionController,
      :last_transaction_content
    )

    post("/transaction", ZarynWeb.API.TransactionController, :new)

    forward(
      "/graphiql",
      Absinthe.Plug.GraphiQL,
      schema: ZarynWeb.GraphQLSchema,
      socket: ZarynWeb.UserSocket
    )

    forward(
      "/",
      Absinthe.Plug,
      schema: ZarynWeb.GraphQLSchema
    )
  end
end

lib/zaryn_web/views/layout_view.ex
defmodule ZarynWeb.LayoutView do
  @moduledoc false
  use ZarynWeb, :view
end

lib/zaryn_web/templates/layout/app.html.eex
<%= @inner_content %>

lib/zaryn_web/templates/layout/live.html.leex
<%= @inner_content %>

lib/zaryn_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "ZARYN" %></title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <div class="container is-fluid">
      <nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item is-size-5 is-uppercase" href="<%= Routes.live_path(@conn, ZarynWeb.ExplorerIndexLive) %>">
              Zaryn
            </a>
            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbar" class="navbar-menu">
            <div class="navbar-end">
    <!-- 
          TODO: implement the listing of transactions through BeaconChain

              <a class="navbar-item" href="<%= Routes.live_path(@conn, ZarynWeb.TransactionListLive) %>">
                 Transactions
              </a>
  -->
            <a class="navbar-item" href="<%= Routes.explorer_path(@conn, :chain) %>">
                Chains
            </a>
            <a class="navbar-item" href="<%= Routes.live_path(@conn, ZarynWeb.NodeListLive) %>">
                Nodes
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                Governance
                </a>
                <div class="navbar-dropdown is-boxed">
                <a class="navbar-item" href="<%= Routes.live_path(@conn, ZarynWeb.CodeViewerLive) %>">
                    Code Viewer
                </a>
                <a class="navbar-item" href="<%= Routes.live_path(@conn, ZarynWeb.CodeProposalsLive) %>">
                    Code Proposals
                </a>
                </div>
            </div>
            </div>
        </div>
    </nav>
    <main class="pt-6">
      <%= @inner_content %>
    </main>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>